// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import '.env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FIREBASE_API_KEY,
    appId: '1:445411832764:android:8832fb91acf9a9c60771b9',
    messagingSenderId: '445411832764',
    projectId: 'robust-chat-865b4',
    storageBucket: 'robust-chat-865b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FIREBASE_API_KEY,
    appId: '1:445411832764:ios:8886b89ad2d1b15c0771b9',
    messagingSenderId: '445411832764',
    projectId: 'robust-chat-865b4',
    storageBucket: 'robust-chat-865b4.appspot.com',
    iosClientId:
        '445411832764-8m9k31lg6jsmk6ganstjp6dffj8q4qu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.robustChatApp',
  );
}
